Multi-Language System.
Ree6-Applications/Ree6 pull request #108
Opened 2022-09-15 10:04 UTC by DxsSucuk

[contributing]: https://github.com/Ree6-Applications/Ree6/blob/master/.github/CONTRIBUTING.md

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This PR allows access to multiple language packs which can allow no english speakers to use Ree6 without Issues!

2022-10-04 08:40 UTC, DenuxPlays commented
What if you use google spreadsheet (download this as a csv file) instead of yml files.
You dont have to make a commit to update a typo for example.
You can update the file for every start of the bot.
Anyone can have read access to it an it would be easier to find typos for people who dont know programming.
And you dont need any file parsee/serializer for that. You can do it in pure java.

2022-10-04 09:37 UTC, DxsSucuk commented
> What if you use google spreadsheet (download this as a csv file) instead of yml files. 
Thats a interesting Idea I might look into it!

> You dont have to make a commit to update a typo for example. You can update the file for every start of the bot. Anyone can have read access to it an it would be easier to find typos for people who dont know programming. 
The YAML file is read only and will be "directly streamed" into the bots Language Manager, which means that if a typo gets fixed you only need to restart the bot.

Thank you for the input, as of right now the System is mostly a "proof-of-concept", there will be alot of changes and I will consider using csv files as supported language file!

2022-10-04 10:10 UTC, DenuxPlays commented
Yes but with google spreadsheet (or any other service where you can download as csv) you can easily access it from everywhere.
I can build the csv system for you it is really simple or I can make a concept of it if you want.
@DxsSucuk

2022-10-04 10:13 UTC, DenuxPlays commented
You can contact me on Discord if you want to talk about it.

2022-10-04 10:18 UTC, DenuxPlays commented
> Feel free to fork Ree6 and implement it 👍 

Ok will start today when I am home.

2022-10-05 23:33 UTC, DxsSucuk commented
This PR will be merge with V2 after finishing it.

2022-10-06 06:59 UTC, DenuxPlays requested changes

2022-10-06 06:59 UTC, DenuxPlays commented on src/main/java/de/presti/ree6/commands/CommandEvent.java
> +    public String getResource(String key, Object... parameters) {
This and all methods in LanguageService should be renamed because it collides with the method that every class inherits from the object class.

2022-10-06 06:59 UTC, DenuxPlays commented on src/main/java/de/presti/ree6/commands/CommandManager.java
> +                    description = LanguageService.getResource(discordLocale, command.getClass().getAnnotation(Command.class).description());
Again method names needs to be changed.

2022-10-06 06:59 UTC, DenuxPlays commented on src/main/java/de/presti/ree6/language/LanguageService.java
> +    }
Rename all these methods.

2022-10-07 11:08 UTC, DxsSucuk commented
Should be all ready now, just gotta document everything.

2022-10-07 12:01 UTC, merged