Added Monkey Command to send a monke gif.
Ree6-Applications/Ree6 pull request #111
Opened 2022-09-16 11:47 UTC by Solastis

[contributing]: https://github.com/Ree6-Applications/Ree6/blob/master/.github/CONTRIBUTING.md

## Pull Request Etiquette

- [ ] I have checked the PRs for upcoming features/bug fixes.
- [ ] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Replace this sentence with general description of what your Pull Request does.

2022-09-16 11:50 UTC, DxsSucuk requested changes

2022-09-16 11:50 UTC, DxsSucuk commented on src/main/java/de/presti/ree6/commands/impl/fun/Monkey.java
> + * A command to get a random dog images.
Does not seem right.

2022-09-16 11:50 UTC, DxsSucuk commented on src/main/java/de/presti/ree6/commands/impl/fun/Monkey.java
> +		JsonObject js = RequestUtility.request(RequestUtility.Request.builder()
Sure that this code even works?

2022-09-16 11:51 UTC, Solastis commented on src/main/java/de/presti/ree6/commands/impl/fun/Monkey.java
> +		JsonObject js = RequestUtility.request(RequestUtility.Request.builder()
no

2022-09-16 12:21 UTC, DxsSucuk requested changes
Code format looks weird?

2022-09-16 12:23 UTC, DxsSucuk commented
> > ??????? Code format looks weird?
> 
> why

If look at the code you will see that there are unneeded spaces which lets it look a bit odd

2022-09-16 12:23 UTC, DxsSucuk commented on src/main/java/de/presti/ree6/commands/impl/fun/Monkey.java
> +		);
This one for example is scuffed.

2022-09-16 12:23 UTC, DxsSucuk commented on src/main/java/de/presti/ree6/commands/impl/fun/Monkey.java
> +		);
The same goes for this call.

2022-09-16 12:31 UTC, DxsSucuk approved these changes

2022-09-18 18:06 UTC, DxsSucuk approved these changes

2022-09-18 18:06 UTC, merged